### ISSUE TITLE
Export All does not export anything

### ISSUE THREAD

**Issue by Scrxtchy** [Microsoft/OpenType-SVG-Font-Editor#3]
Using a pretty well known sample data of `seguiemj.ttf`
Most if not all characters are displayed in the grid view

but the export button does not export anything, or display any errors in the process

**Comment by miguelsousa** [comment]
@Scrxtchy Segoe Emoji does not have an `SVG ` font table, so there's nothing to export. The colors displayed by the glyphs are achieved using Microsoft's color font format, which uses data from the `COLR` and `CPAL` tables.

**Comment by Scrxtchy** [comment]
Ahh, cheers
